version: 2.1

orbs:
  node: circleci/node@5

executors:
  sonar-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/international-payment-system

jobs:
  sonarcloud:
    executor: sonar-executor
    working_directory: ~/international-payment-system
    steps:
      - checkout
      - run:
          name: Download and Install SonarScanner
          command: |
            SONAR_VERSION="5.0.1.3006"
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}-linux.zip
            unzip sonar-scanner-cli.zip -d $HOME
            echo "export SONAR_SCANNER_HOME=$HOME/sonar-scanner-${SONAR_VERSION}-linux" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set up SonarScanner and permissions
          command: |
            chmod +x ${SONAR_SCANNER_HOME}/bin/sonar-scanner
            echo "export PATH=${SONAR_SCANNER_HOME}/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run SonarCloud Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=Server-Samurai-s_international-payment-system \
              -Dsonar.organization=server-samurai-s \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONAR_TOKEN} \
              -Dsonar.branch.name=dev \
              -Dsonar.analysis.mode=publish \
              -Dsonar.alm.enabled=false

workflows:
  build-and-test:
    jobs:
      - sonarcloud:
          filters:
            branches:
              only:
                - dev