version: 2.1
orbs:
  node: circleci/node@5

jobs:
  sonarcloud:
    docker:
      - image: cimg/openjdk:17.0  # Ensure Java 17 is the base image
    working_directory: ~/international-payment-system
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip -d $HOME
            export PATH="$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"
            echo 'export PATH="$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Set Java 17 and Run SonarCloud Analysis
          command: |
            export JAVA_HOME=/usr/local/openjdk-17  # Force the use of Java 17
            export PATH="$JAVA_HOME/bin:$PATH"
            sonar-scanner \
              -Dsonar.projectKey=ST10029256_international-payment-system \
              -Dsonar.organization=server-samurais \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=9e812ea93e5398f93db118eefa377f67d176b364

workflows:
  sonarcloud-analysis:
    jobs:
      - sonarcloud:
          filters:
            branches:
              only:
                - Dylan-Branch
