version: 2.1

orbs:
  node: circleci/node@5

executors:
  node-executor:
    docker:
      - image: node:18.16.0  # Specifying Node version 18.16.0
    working_directory: ~/international-payment-system

  sonar-executor:
    docker:
      - image: circleci/openjdk:11  # Use a generic OpenJDK 11 image
    working_directory: ~/international-payment-system

jobs:
  test-node:
    executor: node-executor
    working_directory: ~/international-payment-system/frontend
    steps:
      - checkout:
          path: ~/international-payment-system
      - run:
          name: Install dependencies
          command: |
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
      - run:
          name: Run tests
          command: npm test --passWithNoTests
      - store_test_results:
          path: ~/international-payment-system/frontend/test-results

  build-node:
    executor: node-executor
    working_directory: ~/international-payment-system/frontend
    steps:
      - checkout:
          path: ~/international-payment-system
      - run:
          name: Install dependencies
          command: |
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: |
            cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  sonarcloud:
    executor: sonar-executor
    working_directory: ~/international-payment-system
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip -d $HOME
            export PATH=$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH
      - run:
          name: Run SonarCloud analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=server-samurai-s \
              -Dsonar.organization=server-samurais \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=9e812ea93e5398f93db118eefa377f67d176b364

workflows:
  build-and-test:
    jobs:
      - test-node:
          filters:
            branches:
              only:
                - Dylan-Branch
      - build-node:
          requires:
            - test-node
          filters:
            branches:
              only:
                - Dylan-Branch
      - sonarcloud:
          requires:
            - build-node
          filters:
            branches:
              only:
                - Dylan-Branch
