version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-node:
    executor: node/default
    working_directory: ~/international-payment-system/frontend
    steps:
      - checkout:
          path: ~/international-payment-system
      - run:
          name: Install dependencies
          command: |
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
      - run:
          name: Run tests
          command: npm test --passWithNoTests

  build-node:
    executor: node/default
    working_directory: ~/international-payment-system/frontend
    steps:
      - checkout:
          path: ~/international-payment-system
      - run:
          name: Install dependencies
          command: |
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: |
            cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  sonarcloud:
    docker:
      - image: cimg/openjdk:17.0
        user: root
    working_directory: ~/international-payment-system
    environment:
      PATH: "$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"
    steps:
      - checkout
      - run:
          name: Install curl
          command: |
            apk update && apk add curl
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip -d $HOME
            chmod +x $HOME/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner
      - run:
          name: Verify SonarScanner Installation
          command: sonar-scanner --version
      - run:
          name: Run SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=server-samurai-s \
              -Dsonar.organization=server-samurais \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=9e812ea93e5398f93db118eefa377f67d176b364

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: '# e.g., ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test-node:
          filters:
            branches:
              only:
                - Dylan-Branch
      - build-node:
          requires:
            - test-node
          filters:
            branches:
              only:
                - Dylan-Branch
      - sonarcloud:
          requires:
            - build-node
          filters:
            branches:
              only:
                - Dylan-Branch