version: 2.1

orbs:
  node: circleci/node@5

executors:
  node-executor:
    docker:
      - image: node:18.16.0
    working_directory: ~/international-payment-system

  sonar-executor:
    docker:
      - image: sonarsource/sonar-scanner-cli:4.6
    working_directory: /usr/src

jobs:
  test-node:
    executor: node-executor
    working_directory: ~/international-payment-system/frontend
    steps:
      - checkout:
          path: ~/international-payment-system
      - run:
          name: Install dependencies
          command: |
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
      - run:
          name: Run tests
          command: npm test --passWithNoTests
      - store_test_results:
          path: ~/international-payment-system/frontend/test-results

  build-node:
    executor: node-executor
    working_directory: ~/international-payment-system/frontend
    steps:
      - checkout:
          path: ~/international-payment-system
      - run:
          name: Install dependencies
          command: |
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: |
            cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  sonarcloud:
    executor: sonar-executor
    steps:
      - checkout
      - run:
          name: Run SonarCloud Analysis
          command: |
            docker run \
              --rm \
              -e SONAR_HOST_URL="https://sonarcloud.io" \
              -e SONAR_LOGIN="${SONAR_TOKEN}" \
              -e SONAR_PROJECT_KEY="server-samurai-s" \
              -e SONAR_ORGANIZATION="server-samurais" \
              -e SONAR_BRANCH_NAME="Dylan-Branch" \
              -v "$(pwd):/usr/src" \
              sonarsource/sonar-scanner-cli

workflows:
  build-and-test:
    jobs:
      - test-node:
          filters:
            branches:
              only:
                - Dylan-Branch
      - build-node:
          requires:
            - test-node
          filters:
            branches:
              only:
                - Dylan-Branch
      - sonarcloud:
          requires:
            - build-node
          filters:
            branches:
              only:
                - Dylan-Branch
